# Generated by Django 6.0.4 on 2026-05-26 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(help_text='Enter a unique username', max_length=150, unique=True)),
                ('age', models.IntegerField(help_text='Enter user age in years')),
                ('is_public', models.BooleanField(default=True, help_text='Designate if this profile is public or private')),
            ],
        ),
    ]
